adding CI for validate peer requirement

diff --git a/.github/workflows/ci-service.yml b/.github/workflows/ci-service.yml
--- a/.github/workflows/ci-service.yml
+++ b/.github/workflows/ci-service.yml
@@ -45,12 +45,38 @@ jobs:
       - name: Check for temporary versions
         uses: Volontariapp/ci-tools/.github/actions/validate-package-versions@main
 
+  validate-peer-requirements:
+    name: Validate Peer Requirements (${{ inputs.service-name }})
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Setup Node & Yarn
+        uses: Volontariapp/ci-tools/.github/actions/setup-node-yarn@main
+        with:
+          node-version: ${{ inputs.node-version }}
+          cache: "yarn"
+
+      - name: Install Dependencies
+        run: yarn install --immutable
+
+      - name: Check Peer Requirements
+        run: |
+          OUTPUT=$(yarn explain peer-requirements)
+          echo "$OUTPUT"
+          if echo "$OUTPUT" | grep -q "✘"; then
+            echo "Critical peer dependency requirements missing! ✘ detected."
+            exit 1
+          fi
+
   repo-deploy-push:
     name: Deploy Repo Submodule Push (${{ inputs.service-name }})
     runs-on: ubuntu-latest
     needs:
       - check
       - validate-versions
+      - validate-peer-requirements
     if: github.ref == 'refs/heads/main'
     steps:
       - name: Checkout Deploy Repository
